BEGIN TRANSACTION;
CREATE TABLE log (id INTEGER PRIMARY KEY, logtype_id INTEGER, person_id INTEGER, start DATETIME, end DATETIME, comment TEXT);
CREATE TABLE logtype (id INTEGER PRIMARY KEY, name TEXT, desc TEXT);
INSERT INTO logtype VALUES(1,'weight','The weight of a person');
INSERT INTO logtype VALUES(2,'blood_pressure','Upper and under pressure (diastolic and systolic)');
INSERT INTO logtype VALUES(3,'gps_tracking','Tracking of GPS coordinates during a certain time interval');
CREATE TABLE logvalue_entries (id INTEGER PRIMARY KEY, unit_id INTEGER, valuetype_id INTEGER);
CREATE TABLE logvalue_entry (id INTEGER PRIMARY KEY, timestamp DATETIME, value NUMERIC);
CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT, dateofbirth DATE);
CREATE TABLE units (id INTEGER PRIMARY KEY, name TEXT, desc TEXT);
INSERT INTO units VALUES(1,'kg','weight');
INSERT INTO units VALUES(2,'s','time');
INSERT INTO units VALUES(3,'m','distance');
INSERT INTO units VALUES(4,'mmHg','pressure');
CREATE TABLE valuetype (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO valuetype VALUES(1,'weight');
INSERT INTO valuetype VALUES(2,'systolic_pressure');
INSERT INTO valuetype VALUES(3,'diastolic_pressure');
INSERT INTO valuetype VALUES(4,'gps_x');
INSERT INTO valuetype VALUES(5,'gps_y');
COMMIT;
